services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: auth_system_app
    restart: always
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    env_file: .env.docker
    dns:
      - 8.8.8.8

  nginx:
    image: nginx:latest
    container_name: auth_system_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: auth_system_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env.docker

  adminer:
    image: adminer
    container_name: auth_system_adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  mysql_data:
